name: Deploy to Production

# mainブランチへのPushでワークフローを実行します
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ステップ1: リポジトリのコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 完全な履歴をチェックアウトして、正確なデプロイを可能にする

      # ステップ2: SSH接続の設定（Secretsに保存したSSH秘密鍵を使用）
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # ステップ3: サーバーのホストキーを既知のホストに追加（より安全な設定）
      - name: Add SSH Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "Host ${{ secrets.SERVER_HOST }}" > ~/.ssh/config
          echo "  Port ${{ secrets.SERVER_PORT }}" >> ~/.ssh/config
          echo "  StrictHostKeyChecking accept-new" >> ~/.ssh/config
          echo "  UserKnownHostsFile ~/.ssh/known_hosts" >> ~/.ssh/config
          chmod 600 ~/.ssh/config
          
          # 明示的にホスト鍵を取得して保存（ポートを指定）
          ssh-keyscan -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts 2>/dev/null

      # ステップ4: ファイルをサーバーにデプロイ
      - name: Deploy to server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          # rsyncでリポジトリのファイルをサーバーへ転送
          # 以下のディレクトリ/ファイルは転送対象外とする：
          # - .git、.github: GitのメタデータおよびCI設定
          # - .env: 環境変数（機密情報）
          # - vendor、node_modules: 依存関係（サーバー側で再インストール）
          rsync -avz --delete \
            --exclude='.git/' \
            --exclude='.github/' \
            --exclude='.env' \
            --exclude='vendor/' \
            --exclude='node_modules/' \
            -e "ssh -p $SERVER_PORT" \
            ./ $SERVER_USER@$SERVER_HOST:$DEPLOY_PATH
            
          echo "ファイル転送が完了しました"

          # サーバー側で追加処理を実行
          # PHPは使わない形で権限設定のみを行う
          ssh -p $SERVER_PORT $SERVER_USER@$SERVER_HOST "cd $DEPLOY_PATH && \
            echo 'サーバー上でファイル権限を設定中...' && \
            find . -type d -exec chmod 755 {} \; && \
            find . -type f -exec chmod 644 {} \; && \
            echo 'ファイル権限の設定が完了しました'"

      # ステップ5: デプロイ結果の通知（成功・失敗に関わらず実行）
      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ デプロイが成功しました！サイトは正常に更新されています。"
          else
            echo "❌ デプロイに失敗しました。ログを確認してください。"
          fi